# Ansible Playbook (ansible-playbook.json)
- hosts: terraform-ansible
#Tarefas a serem executadas...
  tasks:
  - name: criando o arquivo
    copy:
      dest: /home/ubuntu/index.html
      content: <h1> Feito com Ansible </h1>
  - name: criando o servidor
    shell: "nohup busybox httpd -f -p 8080 &"      